### ISSUE TITLE
Couchsurfing.com issue with cookieblock

### ISSUE THREAD

**Issue by juju4** [dibollinger/CookieBlock#17]
When cookieblock is present without site exception, it does not seem possible to make any change/edit.
Web developer tools show return HTTP 422 Unprocessable Content - https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422 and page displays
> The change you wanted was rejected.
> Maybe you tried to change something you didn't have access to.

Request headers cookies don't seem much different.
```
_safe_cookies__known_cookies	"XSRF-TOKEN|_hammertime_session|remember_user_token|ht_utm_campaign|ht_utm_source|ht_utm_medium|ht_utm_content|ht_utm_term"
```
is there a way to identify how cookies are classified and which ones are removed?
don't see a clear match with https://raw.githubusercontent.com/dibollinger/CookieBlock/main/src/ext_data/known_cookies.json

Tested on Firefox 115esr Linux with pages
Edit Profile: add country - https://www.couchsurfing.com/users/profile?id=xxx
Edit Message Template - https://www.couchsurfing.com/message_templates/xxx
Likely need an account which need both registration and pay.

Confirmed not related to Firefox Tracking protection or other browser extension like ublock or privacy badger.
Normal workaround: add an exception for site

**Comment by Bender250** [comment]
Hi!

I tried to reproduce the problem, but it is behind a paywall.

You can check the cookies yourself by clicking CookieBlock icon -> Open Cookie Configuration -> expanding couchsurfing.com. You will see a table of cookies and their purposes. For those that CookieBlock removed, you have the option to "restore" them, if you click that, the removed cookie will be restored - try to reload the target page and see if it changed. Iterate over multiple cookies to find which one (or multiple) causes the issue. If you find these cookies, change their purpose to "Necessary" and go to the top of that CookieBlock page and click Export as JSON. Share that JSON with me please and I will add the exception. 

Expect the table of cookies large on couchsurfing, so it can take a while.

Thanks!

**Comment by juju4** [comment]
For whatever reason, the "Open Cookie Configuration" is dark blue / not clickable in my setup, be it with or without site exception set.
how to restore or understand why?

**Comment by Bender250** [comment]
You have to enable "Keep Track of Cookie History" in the main menu. That will allow CookieBlock caching information (it is not send anywhere), which speeds up the classification of recurring cookies and also allows you better to inspect what CookieBlock does.

**Comment by juju4** [comment]
Thanks. from above list, all currents are identified as necessary except _hammertime_session which is marked advertising.
Once changed this one to necessary and restored it, website works.
Thanks!
