### ISSUE TITLE
Add spanish translation

### ISSUE THREAD

**Issue by 6ig6oy** [dibollinger/CookieBlock#6]
Hello,
I was just wondering if you could add locales/es to your fantastic extension.

It would be interesting to have a website like weblate.org to make translations.

I hope you find the translation useful,
greetings

PD: Sorry, I was unable to open a pull request.
[locales_ES.zip](https://github.com/dibollinger/CookieBlock/files/8374177/locales_ES.zip)

**Comment by Bender250** [comment]
Thank you for the translation! I fixed quotes escaping, but apart from that it seems to work as expected. We will release the new localization soon.

https://github.com/dibollinger/CookieBlock/commit/98688636969c010cbf286b18e4a5707be5d085ce

Note for me for testing new localization in future: easiest is to run `LANGUAGE=es chromium-browser`.
