### ISSUE TITLE
Broken funcionality - list of websites

### ISSUE THREAD

**Issue by jed84** [dibollinger/CookieBlock#7]
I think it would be good to start reporting all the websites which are getting partially broken due to the default settings applied in CookieBlock.
In this case, we could perhaps create a white list?
Ideally, it would be great to report a broken functionality directly via the extension.

My findings:
- linkedin.com: dark mode does not work
- youtube.com: once the user logs in to the service, they are not being remembered (even if their avatar is still shown in the corner)

**Comment by dunatotatos** [comment]
"acct" from stackoverflow.com should be "functionnality".

**Comment by Bender250** [comment]
LinkedIn and StackOverflow (all variants) fixed in https://github.com/dibollinger/CookieBlock/commit/f2e07399423b1b64a39a7e569c8603901a7f8603. This commit shows how the whitelist is maintained.

YouTube is more complicated to debug, for today my time for fixing websites ran out.

**Comment by mbackendal** [comment]
Google Drive keeps showing the error message
"You are not signed in
You are signed out. Sign back in, then click 'Retry'."
despite being signed in. Following the steps and signing in again doesn't help, neither does adding an exception for the domain in the extension. Pausing cookie removal works, however.
