### ISSUE TITLE
Add Japanese translation

### ISSUE THREAD

**Issue by Shitennouji** [dibollinger/CookieBlock#8]
Hi,

I will provide a "Japanese" json file for the extension CookieBlock version 1.0.0.
[CookieBlock locales_ja-JP.zip](https://github.com/dibollinger/CookieBlock/files/8387716/CookieBlock.locales_ja-JP.zip)
.
Best regards

**Comment by Bender250** [comment]
Thank you for the translation! I had to change folder name (locale) ja-JP to ja, else the browser was refusing to show it localized. I hope it is ok. We will release the new localization soon.

Commit: https://github.com/dibollinger/CookieBlock/commit/c20ea193e9553c4dffb1f87c87fdb74ae0f963bc

**Comment by Shitennouji** [comment]
>  I had to change folder name (locale) ja-JP to ja, else the browser was refusing to show it localized.
Oops. I was inadvertent.

It is for global use and will be useful to many users.

I salute your efforts and sincerity.
I look forward to your continued success in the future.
