### ISSUE TITLE
posteid.poste.it missing QR code used for login

### ISSUE THREAD

**Issue by e075e** [dibollinger/CookieBlock#9]
# Steps
- open an Italian government website that requires to login with [SPID](https://it.wikipedia.org/wiki/SPID), for instance
https://portale.agenziaentrate.gov.it/PortaleWeb/home
- click "Entra con SPID"
![entra](https://user-images.githubusercontent.com/15078341/170877924-58876758-2e9d-45bc-ab09-0b6ad3e25272.png)
"
- select "Poste ID"
![posteid](https://user-images.githubusercontent.com/15078341/170877950-73bac5eb-fcff-46ca-9eb8-93fbce8e17f8.png)

and the PosteID login page shows a username and password on the left and a qr code on the right. The last one is used to login through the smartphones without having to put credentials and OTP.

If Cookie Block is active for https://posteid.poste.it, the QR code is not displayed

# workaround
whitelist https://posteid.poste.it

# screenshoots

**with Cookie Block**
![Screenshot 2022-05-29 at 17-30-52 Login IDP](https://user-images.githubusercontent.com/15078341/170878685-eecb534e-130e-4bbd-b901-2fed9031fb3f.png)

----

**without CookieBlock (QR code has been altered for privacy)**
![Screenshot 2022-05-29 at 17-46-29 Login IDP](https://user-images.githubusercontent.com/15078341/170878569-49fc3e24-d34e-4acf-af26-220e25ab403e.png)

**Comment by Bender250** [comment]
I appologize for ignoring this really long, but now I think this website works (it might have been the new model we released with CookieBlock 1.1)
